 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import static Conexion.BBDD.Actu_pass;
import static Conexion.BBDD.comp_contr;

/**
 *
 * @author felip
 */
public class Camb_Contraseña extends javax.swing.JFrame {

    /**
     * Creates new form Camb_Contraseña
     */
    public Camb_Contraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jButton_Conf = new javax.swing.JButton();
        jButton_Canc = new javax.swing.JButton();
        jPasswordField_vieja = new javax.swing.JPasswordField();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jPasswordField_nueva = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanelFondo.setBackground(new java.awt.Color(176, 214, 243));
        jPanelFondo.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));

        jLabelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitulo.setText("Cambio de contraseña");

        jButton_Conf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aceptar/acep_norm.png"))); // NOI18N
        jButton_Conf.setBorder(null);
        jButton_Conf.setBorderPainted(false);
        jButton_Conf.setContentAreaFilled(false);
        jButton_Conf.setFocusPainted(false);
        jButton_Conf.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Aceptar/acep_press.png"))); // NOI18N
        jButton_Conf.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Aceptar/acep_roll.png"))); // NOI18N
        jButton_Conf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConfActionPerformed(evt);
            }
        });

        jButton_Canc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cancelar/canc_norm.png"))); // NOI18N
        jButton_Canc.setBorder(null);
        jButton_Canc.setBorderPainted(false);
        jButton_Canc.setContentAreaFilled(false);
        jButton_Canc.setFocusPainted(false);
        jButton_Canc.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Cancelar/canc_press.png"))); // NOI18N
        jButton_Canc.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Cancelar/canc_roll.png"))); // NOI18N
        jButton_Canc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancActionPerformed(evt);
            }
        });

        jPasswordField_vieja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField_vieja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField_vieja.setText("sdfsdf");

        jLabelTitulo1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTitulo1.setText("Contraseña Antigua");

        jLabelTitulo2.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTitulo2.setText("Contraseña Nueva");

        jPasswordField_nueva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField_nueva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField_nueva.setText("sdfsdf");

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton_Canc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jButton_Conf)
                .addGap(54, 54, 54))
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTitulo)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jLabelTitulo1)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFondoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelFondoLayout.createSequentialGroup()
                                    .addComponent(jLabelTitulo2)
                                    .addGap(14, 14, 14))
                                .addComponent(jPasswordField_nueva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPasswordField_vieja, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_vieja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_nueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Conf)
                    .addComponent(jButton_Canc))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConfActionPerformed
        //Comprobación de contraseña y actualizacion.
        if(comp_contr(jPasswordField_vieja)){
        
            Actu_pass(jPasswordField_nueva);
            dispose();
        }
    }//GEN-LAST:event_jButton_ConfActionPerformed

    private void jButton_CancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_CancActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Camb_Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Camb_Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Camb_Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Camb_Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Camb_Contraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Canc;
    private javax.swing.JButton jButton_Conf;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPasswordField jPasswordField_nueva;
    private javax.swing.JPasswordField jPasswordField_vieja;
    // End of variables declaration//GEN-END:variables
}
