/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Logica.Logica;

import javax.swing.JPanel;

/**
 *
 * @author alumno
 */
public class ReservaVista extends javax.swing.JPanel {

    private JPanel panelLista;
    private Logica logica;
    //private Reserva reserva;
    /**
     * Creates new form ReservaVista
     */
    public ReservaVista() {
        
    }

    public ReservaVista(JPanel panelLista, Logica logica/*, Reserva reserva*/) {
        initComponents();
        this.panelLista = panelLista;
        this.logica = logica;
        /*this.reserva = reserva;*/
    }

    public JPanel getPanelLista() {
        return panelLista;
    }

    public void setPanelLista(JPanel panelLista) {
        this.panelLista = panelLista;
    }

    public Logica getLogica() {
        return logica;
    }

    public void setLogica(Logica logica) {
        this.logica = logica;
    }

//    public Reserva getReserva() {
//        return reserva;
//    }
//
//    public void setReserva(Reserva reserva) {
//        this.reserva = reserva;
//    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelReserva = new javax.swing.JLabel();
        jLabelReservaDato = new javax.swing.JLabel();
        jLabelLugarInicio = new javax.swing.JLabel();
        jLabelLugarInicioDato = new javax.swing.JLabel();
        jLabelLugarFin = new javax.swing.JLabel();
        jLabelLugarFinDato = new javax.swing.JLabel();
        jLabelFechaInicio = new javax.swing.JLabel();
        jLabelFechaInicioDato = new javax.swing.JLabel();
        jLabelFechaFin = new javax.swing.JLabel();
        jLabelFechaFinDato = new javax.swing.JLabel();
        jLabelIcono = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelModeloDato = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelPrecioDato = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(777, 263));

        jLabelReserva.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelReserva.setText("Reserva:");

        jLabelReservaDato.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelReservaDato.setText("1");

        jLabelLugarInicio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelLugarInicio.setText("Lugar inicio:");

        jLabelLugarInicioDato.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelLugarInicioDato.setText("1");

        jLabelLugarFin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelLugarFin.setText("Lugar fin:");

        jLabelLugarFinDato.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelLugarFinDato.setText("1");

        jLabelFechaInicio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelFechaInicio.setText("Fecha inicio:");

        jLabelFechaInicioDato.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelFechaInicioDato.setText("1");

        jLabelFechaFin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelFechaFin.setText("Fecha fin:");

        jLabelFechaFinDato.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelFechaFinDato.setText("1");

        jLabelIcono.setText("Icono");

        jLabelModelo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelModelo.setText("Modelo:");

        jLabelModeloDato.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelModeloDato.setText("1");

        jLabelPrecio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelPrecio.setText("Precio reserva:");

        jLabelPrecioDato.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelPrecioDato.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLugarInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLugarInicioDato))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLugarFin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLugarFinDato))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelModeloDato))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPrecioDato)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIcono)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFechaInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFechaInicioDato))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFechaFin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFechaFinDato)))
                .addGap(198, 198, 198))
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabelReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelReservaDato)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelReserva)
                    .addComponent(jLabelReservaDato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLugarInicio)
                            .addComponent(jLabelLugarInicioDato))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLugarFin)
                            .addComponent(jLabelLugarFinDato)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFechaInicio)
                            .addComponent(jLabelFechaInicioDato))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFechaFin)
                            .addComponent(jLabelFechaFinDato))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIcono)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelModelo)
                            .addComponent(jLabelModeloDato))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecio)
                            .addComponent(jLabelPrecioDato))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFechaFin;
    private javax.swing.JLabel jLabelFechaFinDato;
    private javax.swing.JLabel jLabelFechaInicio;
    private javax.swing.JLabel jLabelFechaInicioDato;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelLugarFin;
    private javax.swing.JLabel jLabelLugarFinDato;
    private javax.swing.JLabel jLabelLugarInicio;
    private javax.swing.JLabel jLabelLugarInicioDato;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelModeloDato;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelPrecioDato;
    private javax.swing.JLabel jLabelReserva;
    private javax.swing.JLabel jLabelReservaDato;
    // End of variables declaration//GEN-END:variables
}
