/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Logica.Logica;
import static Conexion.BBDD.Actu_User;
import static Conexion.BBDD.recuperar;
import Logica.Reserva;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.SwingConstants;



/**
 *
 * @author jolug
 */
public class Usuario extends javax.swing.JFrame {

    
    /**
     * Creates new form Usuario
     */
    public static String usuario="";
    
    Logica logica;
    public Usuario() {
        initComponents();
        jLabelUsuario.setText(usuario);
        logica=new Logica();
        
        //jLabelUsuario.setHorizontalAlignment(SwingConstants.CENTER);
        //jLabelUsuario.setVerticalAlignment(SwingConstants.CENTER);
        try {
            jTextField1_nombre.setText(recuperar(2,usuario));
            jTextField2_apellido.setText(recuperar(3,usuario));
            jTextField2_correo.setText(recuperar(7,usuario));
            jTextField2_direccion.setText(recuperar(4,usuario));
            jTextField2_fecha.setText(recuperar(5,usuario));
            jTextField2_movil.setText(recuperar(6,usuario));
            logica.añadirreservas(Usuario.usuario);
            
        } catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUsuario = new javax.swing.JPanel();
        jPanelLayaut = new javax.swing.JPanel();
        jPanelPerfil = new javax.swing.JPanel();
        jLabelFotoUsuario = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelFechaNacimiento = new javax.swing.JLabel();
        jLabelMovil1 = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        camb_contraseña = new javax.swing.JLabel();
        actualizar = new javax.swing.JLabel();
        jTextField1_nombre = new javax.swing.JTextField();
        jTextField2_apellido = new javax.swing.JTextField();
        jTextField2_direccion = new javax.swing.JTextField();
        jTextField2_fecha = new javax.swing.JTextField();
        jTextField2_movil = new javax.swing.JTextField();
        jTextField2_correo = new javax.swing.JTextField();
        jPanelReservasActivas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPaneReservasActivas = new javax.swing.JScrollPane();
        jPanelReservasActivasPaneles = new javax.swing.JPanel();
        jPanelHistorialReservas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPaneHistorialReservas = new javax.swing.JScrollPane();
        jPanelHistorialReservasPaneles = new javax.swing.JPanel();
        jLabelNReservas = new javax.swing.JLabel();
        jLabelPrecioInvertido = new javax.swing.JLabel();
        jLabelMarcaFavorita = new javax.swing.JLabel();
        jLabesedefavorita1 = new javax.swing.JLabel();
        jLabelNReservasDato = new javax.swing.JLabel();
        jLabelsedefavoritaDato = new javax.swing.JLabel();
        jLabelMarcaFavoritaDato = new javax.swing.JLabel();
        jLabelPrecioInvertidoDato = new javax.swing.JLabel();
        jPanelReservarAhora = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelHerramientas = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelReservasActivasLogo = new javax.swing.JLabel();
        jLabelHistorialReservasLogo = new javax.swing.JLabel();
        jLabelPefilicono = new javax.swing.JLabel();
        jLabelReservarAhora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelUsuario.setBackground(new java.awt.Color(176, 214, 243));

        jPanelLayaut.setLayout(new java.awt.CardLayout());

        jPanelPerfil.setBackground(new java.awt.Color(176, 214, 243));

        jLabelFotoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ad/img/FotoUsuario.png"))); // NOI18N

        jLabelNombre.setBackground(new java.awt.Color(0, 0, 0));
        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jLabelApellidos.setBackground(new java.awt.Color(0, 0, 0));
        jLabelApellidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelApellidos.setText("Apellidos:");

        jLabelDireccion.setBackground(new java.awt.Color(0, 0, 0));
        jLabelDireccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDireccion.setText("Direccion:");

        jLabelFechaNacimiento.setBackground(new java.awt.Color(0, 0, 0));
        jLabelFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelFechaNacimiento.setText("Fecha de nacimiento:");

        jLabelMovil1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMovil1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelMovil1.setText("Movil:");

        jLabelCorreo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCorreo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCorreo.setText("Correo:");

        jLabelUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsuario.setToolTipText("");
        jLabelUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        camb_contraseña.setBackground(java.awt.Color.lightGray);
        camb_contraseña.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        camb_contraseña.setText("  Cambiar Contraseña");
        camb_contraseña.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        camb_contraseña.setOpaque(true);
        camb_contraseña.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                camb_contraseñaMouseMoved(evt);
            }
        });
        camb_contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                camb_contraseñaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                camb_contraseñaMouseExited(evt);
            }
        });

        actualizar.setBackground(java.awt.Color.lightGray);
        actualizar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        actualizar.setText("                Actualizar");
        actualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        actualizar.setOpaque(true);
        actualizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                actualizarMouseMoved(evt);
            }
        });
        actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                actualizarMouseExited(evt);
            }
        });

        jTextField1_nombre.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextField1_nombre.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1_nombre.setText("macaco");
        jTextField1_nombre.setBorder(null);
        jTextField1_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1_nombreMouseClicked(evt);
            }
        });

        jTextField2_apellido.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextField2_apellido.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2_apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2_apellido.setBorder(null);
        jTextField2_apellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2_apellidoMouseClicked(evt);
            }
        });

        jTextField2_direccion.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextField2_direccion.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2_direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2_direccion.setBorder(null);
        jTextField2_direccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2_direccionMouseClicked(evt);
            }
        });

        jTextField2_fecha.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextField2_fecha.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2_fecha.setBorder(null);
        jTextField2_fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2_fechaMouseClicked(evt);
            }
        });
        jTextField2_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_fechaActionPerformed(evt);
            }
        });

        jTextField2_movil.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextField2_movil.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2_movil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2_movil.setBorder(null);
        jTextField2_movil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2_movilMouseClicked(evt);
            }
        });

        jTextField2_correo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextField2_correo.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2_correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2_correo.setBorder(null);
        jTextField2_correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2_correoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelPerfilLayout = new javax.swing.GroupLayout(jPanelPerfil);
        jPanelPerfil.setLayout(jPanelPerfilLayout);
        jPanelPerfilLayout.setHorizontalGroup(
            jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(camb_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPerfilLayout.createSequentialGroup()
                        .addComponent(jLabelCorreo)
                        .addGap(286, 286, 286)
                        .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField2_correo)
                            .addComponent(jTextField2_movil, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2_fecha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2_direccion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2_apellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addComponent(jLabelApellidos)
                    .addComponent(jLabelDireccion)
                    .addComponent(jLabelFechaNacimiento)
                    .addComponent(jLabelMovil1)
                    .addComponent(jLabelNombre))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPerfilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPerfilLayout.createSequentialGroup()
                        .addComponent(jLabelFotoUsuario)
                        .addGap(347, 347, 347))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPerfilLayout.createSequentialGroup()
                        .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(323, 323, 323))))
        );
        jPanelPerfilLayout.setVerticalGroup(
            jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPerfilLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelFotoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2_apellido, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabelApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabelDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabelFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2_movil, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabelMovil1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCorreo))
                .addGap(82, 82, 82)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(camb_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(266, 266, 266))
        );

        jPanelLayaut.add(jPanelPerfil, "Perfilicono");

        jPanelReservasActivas.setBackground(new java.awt.Color(176, 214, 243));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ad/img/ReservasActivas.png"))); // NOI18N

        jScrollPaneReservasActivas.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanelReservasActivasPaneles.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPaneReservasActivas.setViewportView(jPanelReservasActivasPaneles);

        javax.swing.GroupLayout jPanelReservasActivasLayout = new javax.swing.GroupLayout(jPanelReservasActivas);
        jPanelReservasActivas.setLayout(jPanelReservasActivasLayout);
        jPanelReservasActivasLayout.setHorizontalGroup(
            jPanelReservasActivasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReservasActivasLayout.createSequentialGroup()
                .addGroup(jPanelReservasActivasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelReservasActivasLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel3))
                    .addGroup(jPanelReservasActivasLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jScrollPaneReservasActivas, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanelReservasActivasLayout.setVerticalGroup(
            jPanelReservasActivasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReservasActivasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneReservasActivas, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelLayaut.add(jPanelReservasActivas, "ReservasActivasLogo");

        jPanelHistorialReservas.setBackground(new java.awt.Color(176, 214, 243));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ad/img/HistorialDeReservas.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jScrollPaneHistorialReservas.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanelHistorialReservasPaneles.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPaneHistorialReservas.setViewportView(jPanelHistorialReservasPaneles);

        jLabelNReservas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNReservas.setText("Nº de reservas en total:");

        jLabelPrecioInvertido.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelPrecioInvertido.setText("Dinero invertido en las reservas:");

        jLabelMarcaFavorita.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelMarcaFavorita.setText("Marca favorita:");

        jLabesedefavorita1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabesedefavorita1.setText("Sede favorita de reserva:");

        jLabelNReservasDato.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelNReservasDato.setText("0");

        jLabelsedefavoritaDato.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelsedefavoritaDato.setText("No hay datos");

        jLabelMarcaFavoritaDato.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelMarcaFavoritaDato.setText("No hay datos");

        jLabelPrecioInvertidoDato.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelPrecioInvertidoDato.setText("0");

        javax.swing.GroupLayout jPanelHistorialReservasLayout = new javax.swing.GroupLayout(jPanelHistorialReservas);
        jPanelHistorialReservas.setLayout(jPanelHistorialReservasLayout);
        jPanelHistorialReservasLayout.setHorizontalGroup(
            jPanelHistorialReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistorialReservasLayout.createSequentialGroup()
                .addGroup(jPanelHistorialReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHistorialReservasLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanelHistorialReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNReservas)
                            .addComponent(jLabesedefavorita1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelHistorialReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNReservasDato)
                            .addComponent(jLabelsedefavoritaDato))
                        .addGap(103, 103, 103)
                        .addGroup(jPanelHistorialReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMarcaFavorita)
                            .addComponent(jLabelPrecioInvertido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelHistorialReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrecioInvertidoDato)
                            .addComponent(jLabelMarcaFavoritaDato)))
                    .addGroup(jPanelHistorialReservasLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jScrollPaneHistorialReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHistorialReservasLayout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel4)))
                .addGap(102, 102, 102))
        );
        jPanelHistorialReservasLayout.setVerticalGroup(
            jPanelHistorialReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistorialReservasLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jScrollPaneHistorialReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelHistorialReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHistorialReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelHistorialReservasLayout.createSequentialGroup()
                            .addComponent(jLabelPrecioInvertido)
                            .addGap(18, 18, 18)
                            .addComponent(jLabelMarcaFavorita))
                        .addGroup(jPanelHistorialReservasLayout.createSequentialGroup()
                            .addComponent(jLabelNReservas)
                            .addGap(18, 18, 18)
                            .addComponent(jLabesedefavorita1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHistorialReservasLayout.createSequentialGroup()
                            .addComponent(jLabelNReservasDato)
                            .addGap(18, 18, 18)
                            .addComponent(jLabelsedefavoritaDato)))
                    .addGroup(jPanelHistorialReservasLayout.createSequentialGroup()
                        .addComponent(jLabelPrecioInvertidoDato)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMarcaFavoritaDato)))
                .addGap(79, 79, 79))
        );

        jPanelLayaut.add(jPanelHistorialReservas, "HistorialReservasLogo");

        jPanelReservarAhora.setBackground(new java.awt.Color(176, 214, 243));

        jLabel2.setText("Panel de reservar ahora");

        javax.swing.GroupLayout jPanelReservarAhoraLayout = new javax.swing.GroupLayout(jPanelReservarAhora);
        jPanelReservarAhora.setLayout(jPanelReservarAhoraLayout);
        jPanelReservarAhoraLayout.setHorizontalGroup(
            jPanelReservarAhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReservarAhoraLayout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel2)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        jPanelReservarAhoraLayout.setVerticalGroup(
            jPanelReservarAhoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReservarAhoraLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel2)
                .addContainerGap(607, Short.MAX_VALUE))
        );

        jPanelLayaut.add(jPanelReservarAhora, "card6");

        jPanelHerramientas.setBackground(java.awt.Color.lightGray);
        jPanelHerramientas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ad/img/Logo.png"))); // NOI18N
        jPanelHerramientas.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 11, -1, -1));

        jLabelReservasActivasLogo.setBackground(java.awt.Color.lightGray);
        jLabelReservasActivasLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ad/img/ReservasActivas.png"))); // NOI18N
        jLabelReservasActivasLogo.setOpaque(true);
        jLabelReservasActivasLogo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelReservasActivasLogoMouseMoved(evt);
            }
        });
        jLabelReservasActivasLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelReservasActivasLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelReservasActivasLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelReservasActivasLogoMouseExited(evt);
            }
        });
        jPanelHerramientas.add(jLabelReservasActivasLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 234, 194, 126));

        jLabelHistorialReservasLogo.setBackground(java.awt.Color.lightGray);
        jLabelHistorialReservasLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ad/img/HistorialDeReservas.png"))); // NOI18N
        jLabelHistorialReservasLogo.setOpaque(true);
        jLabelHistorialReservasLogo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelHistorialReservasLogoMouseMoved(evt);
            }
        });
        jLabelHistorialReservasLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHistorialReservasLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHistorialReservasLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHistorialReservasLogoMouseExited(evt);
            }
        });
        jPanelHerramientas.add(jLabelHistorialReservasLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 194, -1));

        jLabelPefilicono.setBackground(java.awt.Color.lightGray);
        jLabelPefilicono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ad/img/Perfilicono.png"))); // NOI18N
        jLabelPefilicono.setOpaque(true);
        jLabelPefilicono.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelPefiliconoMouseMoved(evt);
            }
        });
        jLabelPefilicono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPefiliconoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPefiliconoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPefiliconoMouseExited(evt);
            }
        });
        jPanelHerramientas.add(jLabelPefilicono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 123, 194, 110));

        jLabelReservarAhora.setBackground(java.awt.Color.lightGray);
        jLabelReservarAhora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ad/img/ReservarAhora.png"))); // NOI18N
        jLabelReservarAhora.setOpaque(true);
        jLabelReservarAhora.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelReservarAhoraMouseMoved(evt);
            }
        });
        jLabelReservarAhora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelReservarAhoraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelReservarAhoraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelReservarAhoraMouseExited(evt);
            }
        });
        jPanelHerramientas.add(jLabelReservarAhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 194, -1));

        javax.swing.GroupLayout jPanelUsuarioLayout = new javax.swing.GroupLayout(jPanelUsuario);
        jPanelUsuario.setLayout(jPanelUsuarioLayout);
        jPanelUsuarioLayout.setHorizontalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addComponent(jPanelHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelLayaut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanelUsuarioLayout.setVerticalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelLayaut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPefiliconoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPefiliconoMouseClicked
        // TODO add your handling code here:
    CardLayout card = (CardLayout)jPanelLayaut.getLayout();
    card.show(jPanelLayaut, "Perfilicono");
    }//GEN-LAST:event_jLabelPefiliconoMouseClicked

    private void jLabelReservasActivasLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservasActivasLogoMouseClicked
        // TODO add your handling code here:
    CardLayout card = (CardLayout)jPanelLayaut.getLayout();
    card.show(jPanelLayaut, "ReservasActivasLogo");
    logica.añadirReservasActivas(jPanelReservasActivasPaneles,true);


    }//GEN-LAST:event_jLabelReservasActivasLogoMouseClicked

    private void jLabelHistorialReservasLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHistorialReservasLogoMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)jPanelLayaut.getLayout();
        card.show(jPanelLayaut, "HistorialReservasLogo");
        logica.añadirReservasActivas(jPanelHistorialReservasPaneles,false);
        jLabelNReservasDato.setText(logica.calculaNreservas());
        jLabelPrecioInvertidoDato.setText(logica.calculapreciototalreservas());
        jLabelMarcaFavoritaDato.setText(logica.calculamarcafavorita());
        jLabelsedefavoritaDato.setText(logica.calculasedefavorita());
    }//GEN-LAST:event_jLabelHistorialReservasLogoMouseClicked

    private void jLabelReservasActivasLogoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservasActivasLogoMouseMoved
        jLabelReservasActivasLogo.setBackground(Color.GRAY);
    }//GEN-LAST:event_jLabelReservasActivasLogoMouseMoved

    private void jLabelReservasActivasLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservasActivasLogoMouseEntered
        
    }//GEN-LAST:event_jLabelReservasActivasLogoMouseEntered

    private void jLabelReservasActivasLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservasActivasLogoMouseExited
        jLabelReservasActivasLogo.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabelReservasActivasLogoMouseExited

    private void jLabelPefiliconoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPefiliconoMouseEntered
       
    }//GEN-LAST:event_jLabelPefiliconoMouseEntered

    private void jLabelHistorialReservasLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHistorialReservasLogoMouseEntered
        
    }//GEN-LAST:event_jLabelHistorialReservasLogoMouseEntered

    private void jLabelReservarAhoraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservarAhoraMouseEntered
        
    }//GEN-LAST:event_jLabelReservarAhoraMouseEntered

    private void jLabelPefiliconoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPefiliconoMouseExited
        jLabelPefilicono.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabelPefiliconoMouseExited

    private void jLabelHistorialReservasLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHistorialReservasLogoMouseExited
        jLabelHistorialReservasLogo.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabelHistorialReservasLogoMouseExited

    private void jLabelReservarAhoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservarAhoraMouseExited
        jLabelReservarAhora.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabelReservarAhoraMouseExited

    private void jLabelPefiliconoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPefiliconoMouseMoved
        // TODO add your handling code here:
        jLabelPefilicono.setBackground(Color.GRAY);
    }//GEN-LAST:event_jLabelPefiliconoMouseMoved

    private void jLabelReservarAhoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservarAhoraMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)jPanelLayaut.getLayout();
        card.show(jPanelLayaut, "ReservarLogo");
        dispose();
    }//GEN-LAST:event_jLabelReservarAhoraMouseClicked

    private void jLabelHistorialReservasLogoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHistorialReservasLogoMouseMoved
        jLabelHistorialReservasLogo.setBackground(Color.GRAY);
    }//GEN-LAST:event_jLabelHistorialReservasLogoMouseMoved

    private void jLabelReservarAhoraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReservarAhoraMouseMoved
        jLabelReservarAhora.setBackground(Color.GRAY);
    }//GEN-LAST:event_jLabelReservarAhoraMouseMoved

    private void actualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarMouseExited
        actualizar.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_actualizarMouseExited

    private void actualizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarMouseMoved
        actualizar.setBackground(Color.GRAY);
    }//GEN-LAST:event_actualizarMouseMoved

    private void camb_contraseñaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camb_contraseñaMouseExited
        camb_contraseña.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_camb_contraseñaMouseExited

    private void camb_contraseñaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camb_contraseñaMouseMoved
        camb_contraseña.setBackground(Color.GRAY);
    }//GEN-LAST:event_camb_contraseñaMouseMoved

    private void jTextField2_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_fechaActionPerformed

    private void jTextField1_nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1_nombreMouseClicked
        jTextField1_nombre.setText("");
        jTextField1_nombre.setForeground(Color.black);
        
        if(jTextField2_apellido.getText().equals("")){
        
            try {
                jTextField2_apellido.setText(recuperar(3,usuario));
                jTextField2_apellido.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_correo.getText().equals("")){
        
            try {
                jTextField2_correo.setText(recuperar(7,usuario));
                jTextField2_correo.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_direccion.getText().equals("")){
        
            try {
                jTextField2_direccion.setText(recuperar(4,usuario));
                jTextField2_direccion.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_fecha.getText().equals("")){
        
            try {
                jTextField2_fecha.setText(recuperar(5,usuario));
                jTextField2_fecha.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_movil.getText().equals("")){
        
            try {
                jTextField2_movil.setText(recuperar(6,usuario));
                jTextField2_movil.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_jTextField1_nombreMouseClicked

    private void jTextField2_apellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2_apellidoMouseClicked
        jTextField2_apellido.setText("");
        jTextField2_apellido.setForeground(Color.black);
        
        if(jTextField1_nombre.getText().equals("")){
        
            try {
                jTextField1_nombre.setText(recuperar(2,usuario));
                jTextField1_nombre.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_correo.getText().equals("")){
        
            try {
                jTextField2_correo.setText(recuperar(7,usuario));
                jTextField2_correo.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_direccion.getText().equals("")){
        
            try {
                jTextField2_direccion.setText(recuperar(4,usuario));
                jTextField2_direccion.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_fecha.getText().equals("")){
        
            try {
                jTextField2_fecha.setText(recuperar(5,usuario));
                jTextField2_fecha.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_movil.getText().equals("")){
        
            try {
                jTextField2_movil.setText(recuperar(6,usuario));
                jTextField2_movil.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_jTextField2_apellidoMouseClicked

    private void jTextField2_direccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2_direccionMouseClicked
        jTextField2_direccion.setText("");
        jTextField2_direccion.setForeground(Color.black);
        
        if(jTextField1_nombre.getText().equals("")){
        
            try {
                jTextField1_nombre.setText(recuperar(2,usuario));
                jTextField1_nombre.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_correo.getText().equals("")){
        
            try {
                jTextField2_correo.setText(recuperar(7,usuario));
                jTextField2_correo.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_apellido.getText().equals("")){
        
            try {
                jTextField2_apellido.setText(recuperar(3,usuario));
                jTextField2_apellido.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_fecha.getText().equals("")){
        
            try {
                jTextField2_fecha.setText(recuperar(5,usuario));
                jTextField2_fecha.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_movil.getText().equals("")){
        
            try {
                jTextField2_movil.setText(recuperar(6,usuario));
                jTextField2_movil.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_jTextField2_direccionMouseClicked

    private void jTextField2_fechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2_fechaMouseClicked
        jTextField2_fecha.setText("");
        jTextField2_fecha.setForeground(Color.black);
        
        if(jTextField2_apellido.getText().equals("")){
        
            try {
                jTextField2_apellido.setText(recuperar(3,usuario));
                jTextField2_apellido.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_correo.getText().equals("")){
        
            try {
                jTextField2_correo.setText(recuperar(7,usuario));
                jTextField2_correo.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_direccion.getText().equals("")){
        
            try {
                jTextField2_direccion.setText(recuperar(4,usuario));
                jTextField2_direccion.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField1_nombre.getText().equals("")){
        
            try {
                jTextField1_nombre.setText(recuperar(2,usuario));
                jTextField1_nombre.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_movil.getText().equals("")){
        
            try {
                jTextField2_movil.setText(recuperar(6,usuario));
                jTextField2_movil.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_jTextField2_fechaMouseClicked

    private void jTextField2_movilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2_movilMouseClicked
        jTextField2_movil.setText("");
        jTextField2_movil.setForeground(Color.black);
        
        if(jTextField2_apellido.getText().equals("")){
        
            try {
                jTextField2_apellido.setText(recuperar(3,usuario));
                jTextField2_apellido.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_correo.getText().equals("")){
        
            try {
                jTextField2_correo.setText(recuperar(7,usuario));
                jTextField2_correo.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_direccion.getText().equals("")){
        
            try {
                jTextField2_direccion.setText(recuperar(4,usuario));
                jTextField2_direccion.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_fecha.getText().equals("")){
        
            try {
                jTextField2_fecha.setText(recuperar(5,usuario));
                jTextField2_fecha.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField1_nombre.getText().equals("")){
        
            try {
                jTextField1_nombre.setText(recuperar(2,usuario));
                jTextField1_nombre.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_jTextField2_movilMouseClicked

    private void jTextField2_correoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2_correoMouseClicked
        jTextField2_correo.setText("");
        jTextField2_correo.setForeground(Color.black);
        
        if(jTextField2_apellido.getText().equals("")){
        
            try {
                jTextField2_apellido.setText(recuperar(3,usuario));
                jTextField2_apellido.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField1_nombre.getText().equals("")){
        
            try {
                jTextField1_nombre.setText(recuperar(2,usuario));
                jTextField1_nombre.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_direccion.getText().equals("")){
        
            try {
                jTextField2_direccion.setText(recuperar(4,usuario));
                jTextField2_direccion.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_fecha.getText().equals("")){
        
            try {
                jTextField2_fecha.setText(recuperar(5,usuario));
                jTextField2_fecha.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if(jTextField2_movil.getText().equals("")){
        
            try {
                jTextField2_movil.setText(recuperar(6,usuario));
                jTextField2_movil.setForeground(new java.awt.Color(153, 153, 153));
            } catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_jTextField2_correoMouseClicked

    private void actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarMouseClicked
        Actu_User(jTextField1_nombre.getText(),jTextField2_apellido.getText(),jTextField2_direccion.getText(),jTextField2_fecha.getText(),jTextField2_movil.getText(),jTextField2_correo.getText());
    }//GEN-LAST:event_actualizarMouseClicked

    private void camb_contraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camb_contraseñaMouseClicked
        new Camb_Contraseña().setVisible(true);
    }//GEN-LAST:event_camb_contraseñaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualizar;
    private javax.swing.JLabel camb_contraseña;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelFechaNacimiento;
    private javax.swing.JLabel jLabelFotoUsuario;
    private javax.swing.JLabel jLabelHistorialReservasLogo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMarcaFavorita;
    private javax.swing.JLabel jLabelMarcaFavoritaDato;
    private javax.swing.JLabel jLabelMovil1;
    private javax.swing.JLabel jLabelNReservas;
    private javax.swing.JLabel jLabelNReservasDato;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPefilicono;
    private javax.swing.JLabel jLabelPrecioInvertido;
    private javax.swing.JLabel jLabelPrecioInvertidoDato;
    private javax.swing.JLabel jLabelReservarAhora;
    private javax.swing.JLabel jLabelReservasActivasLogo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelsedefavoritaDato;
    private javax.swing.JLabel jLabesedefavorita1;
    private javax.swing.JPanel jPanelHerramientas;
    private javax.swing.JPanel jPanelHistorialReservas;
    private javax.swing.JPanel jPanelHistorialReservasPaneles;
    private javax.swing.JPanel jPanelLayaut;
    private javax.swing.JPanel jPanelPerfil;
    private javax.swing.JPanel jPanelReservarAhora;
    private javax.swing.JPanel jPanelReservasActivas;
    private javax.swing.JPanel jPanelReservasActivasPaneles;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JScrollPane jScrollPaneHistorialReservas;
    private javax.swing.JScrollPane jScrollPaneReservasActivas;
    private javax.swing.JTextField jTextField1_nombre;
    private javax.swing.JTextField jTextField2_apellido;
    private javax.swing.JTextField jTextField2_correo;
    private javax.swing.JTextField jTextField2_direccion;
    private javax.swing.JTextField jTextField2_fecha;
    private javax.swing.JTextField jTextField2_movil;
    // End of variables declaration//GEN-END:variables
}
